export * from './user.model';
export * from './permission.model';
export * from './role.model';
export * from './truck.model';
export * from './trailer.model';
export * from './trip.model';
export * from './fuel-record.model';
export * from './tire.model';
export * from './maintenance.model';
