export enum TruckStatus {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  MAINTENANCE = 'MAINTENANCE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum TrailerStatus {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  MAINTENANCE = 'MAINTENANCE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum TripStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TireStatus {
  GOOD = 'GOOD',
  WORN = 'WORN',
  NEEDS_REPLACEMENT = 'NEEDS_REPLACEMENT',
  REPLACED = 'REPLACED',
}

export enum MaintenanceType {
  OIL_CHANGE = 'OIL_CHANGE',
  TIRE_ROTATION = 'TIRE_ROTATION',
  BRAKE_SERVICE = 'BRAKE_SERVICE',
  ENGINE_SERVICE = 'ENGINE_SERVICE',
  GENERAL_INSPECTION = 'GENERAL_INSPECTION',
  REPAIR = 'REPAIR',
}

export enum VehicleType {
  TRUCK = 'TRUCK',
  TRAILER = 'TRAILER',
}
